/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#bb0028",
        "primary-container": "#e61337",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "secondary": "#6e5c3e",
        "secondary-container": "#f9dfb9",
        "on-secondary-container": "#746243",
        "surface": "#fef9f2",
        "on-surface": "#1d1c18",
        "outline": "#926e6d",
        "outline-variant": "#e7bcbb",
        "background": "#fef9f2",
        "on-background": "#1d1c18",
        "surface-dim": "#ded9d3",
        "surface-bright": "#fef9f2",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#32302c",
        "inverse-on-surface": "#f5f0e9",
        "surface-tint": "#bf0029",
        "primary-fixed": "#ffdad8",
        "primary-fixed-dim": "#ffb3b1",
        "on-primary-fixed": "#410007",
        "on-primary-fixed-variant": "#92001d",
        "secondary-fixed": "#f9dfb9",
        "secondary-fixed-dim": "#dbc39f",
        "on-secondary-fixed": "#261903",
        "on-secondary-fixed-variant": "#554428",
        "tertiary-fixed": "#eee1cb",
        "tertiary-fixed-dim": "#d1c5b0",
        "on-tertiary-fixed": "#211b0d",
        "on-tertiary-fixed-variant": "#4e4635",
        "tertiary": "#635b4a",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#7d7461",
        "on-tertiary-container": "#fffbff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-primary": "#ffb3b1"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      maxWidth: {
        "container-max": "1280px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "48px",
        "base": "8px",
        "gutter": "24px",
        "margin": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "stack-xl": "48px",
        "unit": "8px",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-lg": ["Outfit", "Noto Sans SC", "sans-serif"],
        "body-sm": ["Outfit", "Noto Sans SC", "sans-serif"],
        "body-md": ["Outfit", "Noto Sans SC", "sans-serif"],
        "headline-lg": ["Outfit", "Noto Sans SC", "sans-serif"],
        "headline-md": ["Outfit", "Noto Sans SC", "sans-serif"],
        "title-md": ["Outfit", "Noto Sans SC", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "Noto Sans SC", "sans-serif"],
        "label-md": ["Outfit", "Noto Sans SC", "sans-serif"],
        "label-sm": ["Outfit", "Noto Sans SC", "sans-serif"],
        "display-lg": ["Outfit", "Noto Sans SC", "sans-serif"],
        "display-lg-mobile": ["Outfit", "Noto Sans SC", "sans-serif"],
        "mono-label": ["Outfit", "Noto Sans SC", "sans-serif"],
        "label-caps": ["Outfit", "Noto Sans SC", "monospace"],
        "mono-data": ["Outfit", "Noto Sans SC", "monospace"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "title-md": ["20px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "display-lg-mobile": ["36px", {"lineHeight": "42px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "mono-label": ["11px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "mono-data": ["13px", {"lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
