import sqlite3
import json
import os
import sys

# Set standard output encoding to UTF-8 to prevent GBK errors
sys.stdout.reconfigure(encoding='utf-8')

# Search for database in standard locations
candidates = [
    os.path.join("data", "whisperMe.db"),
    "whisperMe.db",
    os.path.join("..", "data", "whisperMe.db"),
    os.path.join("..", "whisperMe.db")
]
db_path = None
for p in candidates:
    if os.path.exists(p):
        db_path = p
        break

if not db_path:
    print("Database not found in candidates:", candidates)
    sys.exit(1)

print(f"Connecting to database: {db_path}")
conn = sqlite3.connect(db_path)
conn.row_factory = sqlite3.Row
cursor = conn.cursor()

# Query completed tasks that have valid cover images and summaries
cursor.execute("""
    SELECT * FROM tasks 
    WHERE status = 'completed' 
      AND image_url IS NOT NULL 
      AND image_url != ''
    ORDER BY created_at DESC
""")
rows = cursor.fetchall()
print(f"Found {len(rows)} completed tasks with covers.")

mock_tasks = []

for row in rows:
    t = dict(row)
    tid = t["id"]
    
    # Get paragraphs
    cursor.execute("SELECT * FROM paragraphs WHERE podcast_id = ? ORDER BY start_time", (tid,))
    paragraphs = [dict(p) for p in cursor.fetchall()]
    
    # Get cards
    cursor.execute("SELECT * FROM cards WHERE podcast_id = ?", (tid,))
    cards = [dict(c) for c in cursor.fetchall()]

    # Parse JSON fields
    metadata = {}
    if t.get("metadata"):
        try:
            metadata = json.loads(t["metadata"])
        except Exception:
            metadata = {}

    speaker_mappings = {}
    if t.get("speaker_mappings"):
        try:
            speaker_mappings = json.loads(t["speaker_mappings"])
        except Exception:
            speaker_mappings = {}

    qa_history = []
    if t.get("qa_history"):
        try:
            qa_history = json.loads(t["qa_history"])
        except Exception:
            qa_history = []

    # Extract the original public CDN audio URL from metadata if available
    audio_url = ""
    if metadata.get("audio_url") and (metadata["audio_url"].startswith("http://") or metadata["audio_url"].startswith("https://")):
        audio_url = metadata["audio_url"]
    elif t.get("audio_url") and (t["audio_url"].startswith("http://") or t["audio_url"].startswith("https://")):
        audio_url = t["audio_url"]
    
    if not audio_url:
        audio_url = "https://www.w3schools.com/html/horse.mp3"

    mock_task = {
        "id": t["id"],
        "url": t["url"],
        "asr_mode": t.get("asr_mode", "online"),
        "summary_mode": t.get("summary_mode", "online"),
        "title": t["title"],
        "podcast_name": t["podcast_name"],
        "status": t["status"],
        "progress": t["progress"],
        "created_at": t["created_at"],
        "image_url": t["image_url"],
        "transcript": t["transcript"],
        "summary": t["summary"],
        "audio_url": audio_url,
        "metadata": metadata,
        "speaker_mappings": speaker_mappings,
        "paragraphs": paragraphs,
        "cards": cards,
        "qa_history": qa_history
    }
    mock_tasks.append(mock_task)

js_content = f"// Automatically generated by export_mock_data.py\nexport const MOCK_TASKS = {json.dumps(mock_tasks, ensure_ascii=False, indent=2)};\n"

# Output path relative to git root
out_path = os.path.join("frontend", "src", "mockData.js")
if not os.path.exists("frontend"):
    out_path = os.path.join("..", "frontend", "src", "mockData.js")

with open(out_path, "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"✅ Successfully exported {len(mock_tasks)} rich podcast tasks with covers to {out_path}")
conn.close()

