import sqlite3
import json
import os
import sys

# Set standard output encoding to UTF-8 to prevent GBK errors
sys.stdout.reconfigure(encoding='utf-8')

db_path = "whisperMe.db"
if not os.path.exists(db_path):
    # Try parent directory if run from scripts folder
    db_path = os.path.join("..", "whisperMe.db")
    if not os.path.exists(db_path):
        print(f"Database not found at {db_path}")
        exit(1)

conn = sqlite3.connect(db_path)
conn.row_factory = sqlite3.Row
cursor = conn.cursor()

target_ids = ["9fae2ee6-b71a-43b1-8c21-714dcac387ef", "9da70a1a-3fbd-4223-b7f6-bbb975d80f58"]
mock_tasks = []

for tid in target_ids:
    cursor.execute("SELECT * FROM tasks WHERE id = ?", (tid,))
    row = cursor.fetchone()
    if not row:
        print(f"Warning: Task {tid} not found in database.")
        continue
    t = dict(row)
    
    # Get paragraphs
    cursor.execute("SELECT * FROM paragraphs WHERE podcast_id = ? ORDER BY start_time", (tid,))
    paragraphs = [dict(p) for p in cursor.fetchall()]
    
    # Get cards
    cursor.execute("SELECT * FROM cards WHERE podcast_id = ?", (tid,))
    cards = [dict(c) for c in cursor.fetchall()]

    # Parse JSON fields
    metadata = {}
    if t.get("metadata"):
        try:
            metadata = json.loads(t["metadata"])
        except Exception:
            metadata = {}

    speaker_mappings = {}
    if t.get("speaker_mappings"):
        try:
            speaker_mappings = json.loads(t["speaker_mappings"])
        except Exception:
            speaker_mappings = {}

    qa_history = []
    if t.get("qa_history"):
        try:
            qa_history = json.loads(t["qa_history"])
        except Exception:
            qa_history = []

    # Sanitize audio URLs to use a public sample file for testing
    audio_url = "https://www.w3schools.com/html/horse.mp3"

    mock_task = {
        "id": t["id"],
        "url": t["url"],
        "asr_mode": t["asr_mode"],
        "summary_mode": t["summary_mode"],
        "title": t["title"],
        "podcast_name": t["podcast_name"],
        "status": t["status"],
        "progress": t["progress"],
        "created_at": t["created_at"],
        "image_url": t["image_url"],
        "transcript": t["transcript"],
        "summary": t["summary"],
        "audio_url": audio_url,
        "metadata": metadata,
        "speaker_mappings": speaker_mappings,
        "paragraphs": paragraphs,
        "cards": cards,
        "qa_history": qa_history
    }
    mock_tasks.append(mock_task)

js_content = f"// Automatically generated by export_mock_data.py\nexport const MOCK_TASKS = {json.dumps(mock_tasks, ensure_ascii=False, indent=2)};\n"

# Output path relative to git root
out_path = os.path.join("frontend", "src", "mockData.js")
if not os.path.exists("frontend"):
    out_path = os.path.join("..", "frontend", "src", "mockData.js")

with open(out_path, "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"Exported {len(mock_tasks)} tasks to {out_path}")
conn.close()
